// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	dto "YouSightSeeing/backend/internal/app/dto"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// CalculateRouteUseCase is an autogenerated mock type for the CalculateRouteUseCase type
type CalculateRouteUseCase struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, req
func (_m *CalculateRouteUseCase) Execute(ctx context.Context, req dto.CalculateRouteRequest) (dto.CalculateRouteResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 dto.CalculateRouteResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.CalculateRouteRequest) (dto.CalculateRouteResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.CalculateRouteRequest) dto.CalculateRouteResponse); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(dto.CalculateRouteResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.CalculateRouteRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCalculateRouteUseCase creates a new instance of CalculateRouteUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCalculateRouteUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *CalculateRouteUseCase {
	mock := &CalculateRouteUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
