// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	dto "YouSightSeeing/backend/internal/app/dto"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// GetUserUseCase is an autogenerated mock type for the GetUserUseCase type
type GetUserUseCase struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, in
func (_m *GetUserUseCase) Execute(ctx context.Context, in dto.GetUserRequest) (dto.GetUserResponse, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 dto.GetUserResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.GetUserRequest) (dto.GetUserResponse, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.GetUserRequest) dto.GetUserResponse); ok {
		r0 = rf(ctx, in)
	} else {
		r0 = ret.Get(0).(dto.GetUserResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.GetUserRequest) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewGetUserUseCase creates a new instance of GetUserUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGetUserUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *GetUserUseCase {
	mock := &GetUserUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
