// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	dto "YouSightSeeing/backend/internal/app/dto"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// GoogleAuthUseCase is an autogenerated mock type for the GoogleAuthUseCase type
type GoogleAuthUseCase struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, in
func (_m *GoogleAuthUseCase) Execute(ctx context.Context, in dto.GoogleAuthRequest) (dto.GoogleAuthResponse, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 dto.GoogleAuthResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.GoogleAuthRequest) (dto.GoogleAuthResponse, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.GoogleAuthRequest) dto.GoogleAuthResponse); ok {
		r0 = rf(ctx, in)
	} else {
		r0 = ret.Get(0).(dto.GoogleAuthResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.GoogleAuthRequest) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewGoogleAuthUseCase creates a new instance of GoogleAuthUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGoogleAuthUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *GoogleAuthUseCase {
	mock := &GoogleAuthUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
