// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	dto "YouSightSeeing/backend/internal/app/dto"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// LogoutUseCase is an autogenerated mock type for the LogoutUseCase type
type LogoutUseCase struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, in
func (_m *LogoutUseCase) Execute(ctx context.Context, in dto.LogoutRequest) (dto.LogoutResponse, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 dto.LogoutResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.LogoutRequest) (dto.LogoutResponse, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.LogoutRequest) dto.LogoutResponse); ok {
		r0 = rf(ctx, in)
	} else {
		r0 = ret.Get(0).(dto.LogoutResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.LogoutRequest) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewLogoutUseCase creates a new instance of LogoutUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLogoutUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *LogoutUseCase {
	mock := &LogoutUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
