// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	dto "YouSightSeeing/backend/internal/app/dto"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// RefreshTokenUseCase is an autogenerated mock type for the RefreshTokenUseCase type
type RefreshTokenUseCase struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, in
func (_m *RefreshTokenUseCase) Execute(ctx context.Context, in dto.RefreshTokenRequest) (dto.RefreshTokenResponse, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 dto.RefreshTokenResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.RefreshTokenRequest) (dto.RefreshTokenResponse, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.RefreshTokenRequest) dto.RefreshTokenResponse); ok {
		r0 = rf(ctx, in)
	} else {
		r0 = ret.Get(0).(dto.RefreshTokenResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.RefreshTokenRequest) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRefreshTokenUseCase creates a new instance of RefreshTokenUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRefreshTokenUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *RefreshTokenUseCase {
	mock := &RefreshTokenUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
