// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	dto "YouSightSeeing/backend/internal/app/dto"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// UpdateUserPictureUseCase is an autogenerated mock type for the UpdateUserPictureUseCase type
type UpdateUserPictureUseCase struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, in
func (_m *UpdateUserPictureUseCase) Execute(ctx context.Context, in dto.UpdateUserPictureRequest) (dto.UpdateUserPictureResponse, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 dto.UpdateUserPictureResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.UpdateUserPictureRequest) (dto.UpdateUserPictureResponse, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.UpdateUserPictureRequest) dto.UpdateUserPictureResponse); ok {
		r0 = rf(ctx, in)
	} else {
		r0 = ret.Get(0).(dto.UpdateUserPictureResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.UpdateUserPictureRequest) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewUpdateUserPictureUseCase creates a new instance of UpdateUserPictureUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUpdateUserPictureUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *UpdateUserPictureUseCase {
	mock := &UpdateUserPictureUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
