// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	dto "YouSightSeeing/backend/internal/app/dto"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// UpdateUserUseCase is an autogenerated mock type for the UpdateUserUseCase type
type UpdateUserUseCase struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, in
func (_m *UpdateUserUseCase) Execute(ctx context.Context, in dto.UpdateUserRequest) (dto.UpdateUserResponse, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 dto.UpdateUserResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.UpdateUserRequest) (dto.UpdateUserResponse, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.UpdateUserRequest) dto.UpdateUserResponse); ok {
		r0 = rf(ctx, in)
	} else {
		r0 = ret.Get(0).(dto.UpdateUserResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.UpdateUserRequest) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewUpdateUserUseCase creates a new instance of UpdateUserUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUpdateUserUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *UpdateUserUseCase {
	mock := &UpdateUserUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
