// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	entity "YouSightSeeing/backend/internal/domain/entity"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// GoogleVerifier is an autogenerated mock type for the GoogleVerifier type
type GoogleVerifier struct {
	mock.Mock
}

// VerifyToken provides a mock function with given fields: ctx, token
func (_m *GoogleVerifier) VerifyToken(ctx context.Context, token string) (*entity.GoogleClaims, error) {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for VerifyToken")
	}

	var r0 *entity.GoogleClaims
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entity.GoogleClaims, error)); ok {
		return rf(ctx, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entity.GoogleClaims); ok {
		r0 = rf(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.GoogleClaims)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewGoogleVerifier creates a new instance of GoogleVerifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGoogleVerifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *GoogleVerifier {
	mock := &GoogleVerifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
