// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	entity "YouSightSeeing/backend/internal/domain/entity"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// RouteCalculator is an autogenerated mock type for the RouteCalculator type
type RouteCalculator struct {
	mock.Mock
}

// CalculateRoute provides a mock function with given fields: ctx, req
func (_m *RouteCalculator) CalculateRoute(ctx context.Context, req entity.ORSRequest) (entity.Route, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CalculateRoute")
	}

	var r0 entity.Route
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.ORSRequest) (entity.Route, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.ORSRequest) entity.Route); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(entity.Route)
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.ORSRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRouteCalculator creates a new instance of RouteCalculator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRouteCalculator(t interface {
	mock.TestingT
	Cleanup(func())
}) *RouteCalculator {
	mock := &RouteCalculator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
